#! /bin/sh

set -e

case "$1" in
    configure)
	if ! getent passwd buildbot>/dev/null; then
	    echo "Creating/updating buildbot user account..."
	    adduser --home /var/lib/buildbot \
		--gecos "BuildBot system user" \
		--system \
		--quiet --disabled-password buildbot
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

install-info --quiet --section "Development" "Development" \
    /usr/share/info/buildbot.info.gz


#DEBHELPER#

exit 0


